### ISSUE TITLE
Merging with / using things-cli?

### ISSUE THREAD

**Issue by AlexanderWillner** [KalebHawkins/Things3-2-Project#1]
Thanks for the code. We might want to discuss whether it makes sense to use [things.py](https://github.com/thingsapi/things.py) / [things-cli](https://github.com/thingsapi/things-cli) here and even merge the code. What do you think?

**Comment by KalebHawkins** [comment]
This was really a hobby project for me. I needed a way to export my projects to hand over to project managers in a more friendly way then markdown. It was a very defined use case. 

However, I would be interested in discussing more.

1. What are the project goals for things.py/things-cli?
2. Would we want to port to Swift of leave everything as Python?

**Comment by AlexanderWillner** [comment]
> This was really a hobby project for me.

Same here ;)

> 1. What are the project goals for things.py/things-cli?

From what I see, quite similar to your approach. It's a Python port of [things.sh](https://github.com/AlexanderWillner/things.sh) to act as a first application of the Python library [things.py](https://github.com/thingsapi/things.py) to query and export (`json`, `csv`, `txt`, opml`) the Things DB from the CLI. 

> 2. Would we want to port to Swift of leave everything as Python?

It seems to be that the objective of both tools are very similar, however, the current CLI probably does not reflect your workflow right now (filter by project). But this could easily be extended.

I used something like this to compare the shell based version with the python based version (adopted for the swift based version):

```shell
#!/usr/bin/env bash

#readonly commands_sh="inbox today upcoming projects tags due trashed logbook cancelled next completed all"
#readonly commands_py="inbox today upcoming projects tags deadlines trash logbook canceled anytime completed all"
readonly commands_py=(  areas projects )
readonly commands_swift=( "list areas" "list projects" )
export THINGSDB=${THINGSDB:-test/Things.sqlite3}

run() {
    local bin="$1"
    shift
    local commands=("$@")
    local result="$(mktemp)"
    local timing="$(mktemp)"
    echo "$bin:"
    for command in "${commands[@]}"; do
      time (eval $bin $command > $result) > $timing 2>&1
      duration=$(grep real $timing|awk '{print $2}')
      results=$(cat $result|wc -l|xargs)
      echo "  - Command: $command. Results: $results. Duration: $duration"
    done
}

#run things.sh "$commands_sh"
run things-cli "${commands_py[@]}"
run .build/release/things3 "${commands_swift[@]}"
```

**Comment by KalebHawkins** [comment]
>     Same here ;)

Your hobby projects far exceed mine lol. I lack a lot of experience so my development process is a little slower until I start feeling comfortable with whatever framework/library I am using at the time.

> It seems to be that the objective of both tools are very similar, however, the current CLI probably does not reflect your workflow right now (filter by project). But this could easily be extended.

You are right about the same idea. At one point I did consider attempting a full blown CLI interface for the ThingsDB. At the time there wasn't enough time for me to plan it out and the scope was not manageable for me. 

My Python knowledge is minimal and my shell scripting is basic at best.. That is why I asked about the porting to Swift. It is just a personal language preference. 

I do really like the things.sh you have. I am particularly interested in the charting and the Markdown workflow in the things.sh repo you have. I would be interested in doing a rewrite of my tools to build an API to make calls to the ThingsDB. Then build the CLI on top of that. 

> "_...probably does not reflect your workflow right now..._"

I didn't really have a workflow. I noticed you had automated unit tests, CI/CD, and automated doc generation among a few other things I would like to get my hands into and learn. I love programming but the DevOps tooling is not something I have skills in but would like to learn. I am familiar with the ideas and concepts of the different tools I just haven't put them into practice. So my _"workflow"_ is code -> compile -> test -> debug -> repeat. I do try to structure clean code and plan out reusable chunks of code but as for creating unit tests I am never sure what exactly to test for or how to test for certain things.

Sorry I am rambling. I would be interested in collaborating on a larger project refactoring what I have created. Personally I would like to extend as well. You let me know how we can proceed.

**Comment by AlexanderWillner** [comment]
With `workflow` I meant how you use your `cli` internally for your needs ;) Maybe you can give Release 0.0.8 a try to check if  `things-cli` could replace your tool (I added a filter for projects).

**Comment by KalebHawkins** [comment]
Sorry for the late response. I'll give it a try at some point and let you know. I haven't had a ton of free time so I don't know when that might be.

**Comment by KalebHawkins** [comment]
Marking as stale. If further discussion is needed/wanted please open new issue.
